# This is the configuration used to check the rubocop source code.

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'db/migrate/20221003114854_devise_create_users.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/jobs/export_bookings_csv_job.rb'
    - 'app/controllers/bookings_controller.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

RSpec/NestedGroups:
  Exclude:
    - 'spec/requests/admin/room_photos_spec.rb'
    - 'spec/requests/admin/rooms_spec.rb'
    - 'spec/requests/admin/reviews_spec.rb'
    - 'spec/requests/admin/bookings_spec.rb'